### ISSUE TITLE
Format for stLFR LinkedReads

### ISSUE THREAD

**Issue by Ellis-Anderson** [bcgsc/physlr#128]
Hello,

I was just curious if the formatting for stLFR LinkedReads needed to be altered before use, similarly to how ARCs requires the formatting to be changed from `>Readname#barcode` to `>Readname BX:Z:barcode`

Thanks,
Ellis

**Comment by jowong4** [comment]
@Ellis-Anderson 

No, we auto detect the read header for 10X or stLFR barcodes. We do need you to extract it from the reads though. We have small test in https://github.com/bcgsc/physlr/blob/master/src/Makefile called check-physlr-index-stLFR If you are interested in confirming it on your own data.

**Comment by Ellis-Anderson** [comment]
@jowong4 

Thanks! As a follow up, I noticed you only specify reads once - does this mean for PE reads you expect an interleaved fastq format?

Best,
Ellis

**Comment by jowong4** [comment]
> does this mean for PE reads you expect an interleaved fastq format?
Yes. We do not use any PE information so we basically treat the file as SE reads.
