### ISSUE TITLE
Support/distinction of other linked-read technologies

### ISSUE THREAD

**Issue by pdimens** [bcgsc/physlr#196]
Hello, I'm interested in incorporating this tool into [Harpy](https://www.github.com/pdimens/harpy), which is specific to haplotagging-style linked reads. The documentation provides the option for 10x and stFLR protocol types, but not other varieties like haplotagging or TELLseq. 

My question is: is there an appreciable difference of what the two protocols alter within physlr and would it be possible to add support for haplotagging-style barcodes? The haplotagging barcodes are still provided in the `BX:Z` tag, but are in the format `AxxCxxBxxDxx` where each `xx` is an integer between 0-99 _e.g._ `A02C96B34D51`.

Sort of related to that, is that deconvolved barcodes may feature a hyphenated ending (e.g. `BX:Z:<barcode>-1`) or an additional `MI:i:` tag of a simple integer indicating the unique molecule those barcodes are said to be associated with (e.g. `MI:i:41` and `MI:i94122`). Is there value in prioritizing the MI:i tag, if present, over the BX:Z tag?

**Comment by lcoombe** [comment]
Hi @pdimens,

Sorry for the delay in getting back to you!

As long as the 'barcode' is in the format. `BX:Z:<barcode>`, it will be recognized by the parsing software in physlr. 
Any distinct string for the "barcode" section will be recognized as a different barcode - but any `MI:I` tag isn't recognized. So if you want to consider different barcode+molecule tags as distinct 'barcodes', then you'd have to alter the barcode part to contain that identifier - that is what we have done in the past when, for example, we had different chromium libraries that we wanted to use together.

I hope that helps - thank you for your interest in Physlr!
Lauren

**Comment by pdimens** [comment]
Does `physlr` distinguish when a barcode is invalidated? For example, when any of the segments of a haplotag barcode feature `00`, e.g. `A51C00B18D91`

**Comment by lcoombe** [comment]
No, it doesn't do any checking of the barcode values - it will just take the full string (from the expected barcode format) as the barcode. So, if you want some barcodes to be ignored (if they are invalid, etc), you'd need to do some pre-filtering.

**Comment by pdimens** [comment]
Understood, thank you!

**Comment by pdimens** [comment]
What does the `platform=` specification change about how `physlr` functions? There seems to be a `10x` and `stflr` option, but what differences are there to them? If I was to use haplotag data, what platform would I specify?

**Comment by lcoombe** [comment]
You're asking about the `protocol=` option, right?

Specifying `stlfr` or `10x` changes the default value for the `m` parameter, which is the % of edges to remove in the overlap graph. Basically, we added those presets to set this parameter to values that we empirically found worked well across different datasets (More detail about the settings is on the help page).

You may want to try different values of `m` to see what works best for your haplotag data - we haven't worked with this data, so it's hard to give a more specific suggestion!

**Comment by pdimens** [comment]
Ah sorry, you're right, I was referring to `protocol=`. That makes sense, thank you for the clarification!
