### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by sjackman** [bcgsc/physlr#2]
Related JIRA ticket: https://www.bcgsc.ca/jira/browse/BTL-1250

- [ ] Characterize linked reads, ie. extent of molecule overlaps, etc @lcoombe 
- [ ] Identify repeat *k*-mers and minimizers using ntHit @afshinfard 
- [ ] Create a Python interface to ntHash @mohamadi
- [x] Create a minimizer sketch of each barcode @sjackman 
- [ ] Index the sketches and identify candidate barcode overlaps @benvvalk
- [ ] Estimate the Jaccard similarity of each barcode pair
- [X] Create a graph of barcode overlaps @sjackman
- [x] Partition the adjacent barcodes (edges) of each barcode into connected communities @sjackman 
- [ ] Create a new graph of molecules and molecule overlaps
- [x] Reassign minimizers/reads to the molecules @lcoombe 
- [ ] ~~Identify transitive edges and remove/retain them~~
- [x] Determine a linear ordering of the molecules (layout the graph) @sjackman 
- [x] Partition the molecules into subgraphs of components and unambiguous paths @sjackman
- [ ] Assemble partitions of molecules @lcoombe

Notes: it's ok to work on same problem as someone else. Above are physlr tasks, but feel free to add tasks that pertain to the more general utilization of linked-reads in assembly .

# Tools

- NetworkX Python graph library

# Datasets

- *E. coli* LRsim
- *C. elegans* LRsim
- NA12878 Chromium
- NA24143 (HG004) Chromium
- Fruit fly Chromium
  - Chromium `/projects/btl_scratch/sjackman/physlr/data/f1.fq.gz`
  - Reference `/projects/btl_scratch/sjackman/physlr/data/fly/fly.fa`
- Zebrafish
  - Chromium `/projects/btl_scratch/sjackman/physlr/data/fish.fq.gz`
  - Reference `/projects/btl_scratch/sjackman/physlr/data/fish/z11.fa`
- *Picea sitchensis* plastid Chromium
  - Chromium `/projects/btl_scratch/sjackman/physlr/HYN5VCCXX_4cp.fq.gz`
  - Reference `/projects/btl_scratch/sjackman/physlr/psitchensiscp/psitchensiscp.fa`

**Comment by aafshinfard** [comment]
Closing this old issue.
