### ISSUE TITLE
Maplr: Mapping linked read molecules directly to a reference genome sequence

### ISSUE THREAD

**Issue by sjackman** [bcgsc/physlr#3]
1. Index the (k,w) minimizers of the reference. (set k and w for ~1 minimizer per 128 bp, can be tweaked for sensitivity/specificity)
2. Compute the set of minimizers, ~1 per read, for each barcode.
3. Find the minimum tiling set of intervals on the reference genome that account for all (or nearly all) of the minimizers observed in the reads of one barcode.
4. Smith-waterman alignment of the first and last read of each molecule to determine the exact start and end coordinate of each molecule (optional)

**Comment by aafshinfard** [comment]
closing this old issue.
